onepageend2/Models/Catagory.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace onepageend2.Models
{
    public class Catagory
    {
        public int id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Text { get; set; }
        
        
      

    }
}

onepageend2/Areas/Menege/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace onepageend2.Areas.Menege.Controllers
{
    [Area("Menege")]
    public class DashBoardController : Controller
    {
      
        public IActionResult Index()
        {
            return View();
        }

    }
}

onepageend2/Areas/Menege/Controllers/TableController.cs
using Microsoft.AspNetCore.Mvc;
using onepageend2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace onepageend2.Areas.Menege.Controllers
{
    public class TableController : Controller
    {
        [Area("Menege")]
       
            public IActionResult Index()
            {
                return View();
            }

        
    }
}
   // {
   //[Area("Menege")]
   //public AppContext _context;
   //public IActionResult Index()
   //  {
   //return View();
   //  }
   //[HttpPost]
   //[ValidateAntiForgeryToken]
   //  public ActionResult Create(Catagory catagory)
   //{



//  }
// public ActionResult Delete(int id)
// {
// var data = _context.Catagories.Where(x => x.CatagoryId == id).FirstOrDefault();
// _context.Employees.Remove(data);
//  _context.SaveChanges();

// return RedirectToAction("index");
// }
// [HttpPost]
// public ActionResult Edit(int id)
//{
//     var data = _context.Catagories.Where(x => x.CatagoryId == id).FirstOrDefault();
//        if (data != null)  
// {  

// _context.SaveChanges();  
// }
//   

//}

//}

onepageend2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace onepageend2.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }


       
    }
}

onepageend2/Areas/Menege/Views/DashBoard/Index.cshtml
<h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

onepageend2/Areas/Menege/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Blank</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item"asp-controller="Table" asp-action="Index">Catagory</a>
                        <a class="collapse-item" href="cards.html">Cards</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
           
                          
                   
                    

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()

                </div>
                <!-- End of Main Content -->
                <!-- Footer -->
              
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->

        </div>
        <!-- End of Page Wrapper -->
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="login.html">Logout</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="~/vendor/jquery/jquery.min.js"></script>
        <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

onepageend2/Areas/Menege/Views/Table/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

onepageend2/Areas/Menege/Views/Table/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

onepageend2/Areas/Menege/Views/Table/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

onepageend2/Areas/Menege/Views/Table/Index.cshtml
<table  class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td></td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td colspan="2">Larry the Bird</td>
            <td></td>
        </tr>
    </tbody>
</table>

onepageend2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<main class="boxmain">
    <div class="container">
        <div class="row">
            <div class="classmaintext">
                <h1>SERVICES</h1>
                <h3>Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
            <div class="classcard">
                <div class="col-md-4 class2 ">
                    <i class="fa-solid fa-basket-shopping"></i>
                    <h1>
                        E-Commerce
                    </h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
                    </p>
                </div>
                <div class="col-md-4 class2 ">
                    <i class="fa-solid fa-display"></i>
                    <h1>
                        Responsive Design
                    </h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
                    </p>
                </div>
                <div class="col-md-4 class2">
                    <i class="fa-solid fa-key"></i>
                    <h1>
                        E-Commerce
                    </h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.
                    </p>
                </div>
            </div>
        </div>
    </div>

</main>
<section class="crad">
    <div class="container">
        <div class="row">
            <div class="classradtext">
                <h1>PORTFOLIO</h1>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
            </div>
            <div class="col-md-4 classw">
                <img src="~/assets/img/roundicons.jpg" alt="">
                <h1>Round Icons</h1>
                <p>Graphic Design</p>
            </div>
            <div class="col-md-4 classw">
                <img src="~/assets/img/startup-framework.jpg" alt="">
                <h1>Round Icons</h1>
                <p>Graphic Design</p>
            </div>
            <div class="col-md-4 classw">
                <img src="~/assets/img/golden.jpg" alt="">
                <h1>Round Icons</h1>
                <p>Graphic Design</p>
            </div>
            <div class="col-md-4 classw">
                <img src="~/assets/img/roundicons.jpg" alt="">
                <h1>Round Icons</h1>
                <p>Graphic Design</p>
            </div>
            <div class="col-md-4 classw">
                <img src="~/assets/img/roundicons.jpg" alt="">
                <h1>Round Icons</h1>
                <p>Graphic Design</p>
            </div>
            <div class="col-md-4 classw">
                <img src="~/assets/img/roundicons.jpg" alt="">
                <h1>Round Icons</h1>
                <p>Graphic Design</p>
            </div>
        </div>
    </div>
</section>>

onepageend2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/assets/css/style.css">

</head>
<body>
    <header id="2" class="header1">
        <div class="container">
            <div class="row">
                <div class="classnaV">
                    <div class="container">
                        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                            <div class="container-fluid">
                                <a class="navbar-brand" href="#">Agencye</a>
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav me-auto mb-2  class1">
                                        <li class="nav-item">
                                            <a class="nav-link active" aria-current="page" href="#1">Services</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link active" aria-current="page" href="#2">Portufolio</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#3">About3</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">Team</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="#">CONTAC</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
                <div class="boxstext">
                    <h2>
                        Welcome To Our Studio!
                    </h2>
                    <h1>
                        IT'S NICE TO MEET YOU
                    </h1>
                    <div class="clasbutton">
                        <button>
                            TELL MEE MORE
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </header>
    @RenderBody()
    <footer id="4" class="footer">
        <div class="container">
            <div class="row">
                <div class="footertext">
                    <h1>
                        CONTACT US
                    </h1>
                    <p>Lorem ipsum dolor sit amet consectetur.</p>
                </div>
                <div class="col-md-6 footermain">
                    <div class="inputclass">
                        <input type="text" placeholder="YOUR Name  "><br>
                    </div>
                    <div class="inputclass">
                        <input type="text" placeholder="YOUR EMAIL  "><br>
                    </div>
                    <div class="inputclass">
                        <input type="text" placeholder="YOUR PHONE  "><br>
                    </div>

                    
                </div>
                <div class="col-md-6 footermain2">
                    <input type="text" placeholder="YOUR MESSAGE  ">

                </div>
                <div class="classbuttonfooter">
                    <button>
                        SEND MESSAGE
                    </button>
                </div>
            </div>

        </div>

    </footer>
    <footer id="3" class="end">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h4>Copyright © All Rights Reserved</h4>
                </div>
                <div class="col-md-4 iconclass">
                    <i class="fa-brands fa-facebook"></i>
                    <i class="fa-brands fa-twitter"></i>
                    <i class="fa-brands fa-linkedin-in"></i>
                </div>
                <div class="col-md-4 classateq">
                    <a href="">Privacy Polic</a>
                    <a href="">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/assets/js/scrips.js"></script>
</body>
</html>